# Change these first
owner: eddyv # Your GitHub organization or username, where this repository lives
repo: voila-upptime # The name of this repository

sites:
  - name: MetaLingo
    url: http://metalingo.ca/
  - name: MetaLingo - API
    url: https://api.metalingo.ca/actuator/health
  - name: test endpoint
    url: https://96d0-174-95-87-6.ngrok-free.app/
    headers:
      - "ngrok-skip-browser-warning: 1"
assignes:
  - eddyv

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /voila-upptime
  logoUrl: https://storage.googleapis.com/metalingo-dev/web-assets/home-page/logos/mainLogo.png
  name: MetaLingo
  introTitle: "**MetaLingo**"
  introMessage: Engage with live, expert teachers in an interactive, online collaborative environment, tailored for ages 7-15. Experience a blend of real-time academic support
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
